services:
  liveblocks:
    build:
      context: .
      dockerfile: liveblocks-dev.Dockerfile
    ports:
      - "1153:1153"
    volumes:
      - liveblocks-data:/app/.liveblocks

volumes:
  liveblocks-data:
